### ISSUE TITLE
Canada

### ISSUE THREAD

**Issue by Andy1996247** [adil6572/YP-business-scraper#1]
Why can't I scrap data from Canada or other places except the USA? How would one make this work?

**Comment by adil6572** [comment]
You cannot scrape data from another country because the scraper is specifically designed to extract data only from https://www.yellowpages.com/. However, the Yellow Pages of Canada is available at https://www.yellowpages.ca/, which has a different website structure. To extract data from this source, you would need to modify the scraper accordingly.

**Comment by Andy1996247** [comment]
> You cannot scrape data from another country because the scraper is specifically designed to extract data only from https://www.yellowpages.com/. However, the Yellow Pages of Canada is available at https://www.yellowpages.ca/, which has a different website structure. To extract data from this source, you would need to modify the scraper accordingly.

thanks for the reply. i understand would you be open  to showing an example?
